version: '3.9'
services:
# ---------------------UI-------------------------------
  ui_app:
    container_name: mentoring_app
    build: ./codesharing/
    restart: always
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
# ------------------------------------------------------
# ----------------- Backend --------------------------------
  backend:
    container_name: backend_api
    build: ./backend
    restart: always
    ports:
      - '5050:12345'
    volumes:
      - ./backend:/backend
    depends_on:
      - backend_db
    environment:
      - DB_URL=postgresql://postgres:postgres@backend_db:5432/postgres

  backend_db:
    container_name: backend_db
    image: postgres:12
    restart: always
    expose:
      - "5432"
    ports:
      - "4567:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: -p 5432
# ------------------------------------------------------